### ISSUE TITLE
Use query params instead of path params in schedules controller

### ISSUE THREAD

**Issue by sheminanto** [amith-vp/Kerala-Private-Bus-Timing-API#2]
It's better to use query params instead of using dynamic segments in the route.
https://github.com/amith-vp/Kerala-Private-Bus-Timing-API/blob/3b3e626399182f69d209c2637772acdf9b95bd67/config/routes.rb#L5

The final code will look like:
```rb
resources :schedules, only: :index
```

Expected URL will be like:
`https://localhost/api/v1/schedules?departure=From&destination=To`

https://github.com/amith-vp/Kerala-Private-Bus-Timing-API/blob/3b3e626399182f69d209c2637772acdf9b95bd67/app/controllers/api/v1/schedules_controller.rb#L8

Also, let's URL encode the parameters rather than using an underscore instead of space, rails will automatically decode it. 
(URL encoding will be  handled by browser/axios automatically)

**Comment by sheminanto** [comment]
@amith-vp: Please check the suggestion.

**Comment by amith-vp** [comment]
Thanks for your suggestions,
Initially, I used query parameters for departure  and destination. e02a79b64d077ac09733eeeb449967d23b7a7051

Then switched to dynamic routes for better readability and cleaner URLs, especially with longer bus station names.
If using query parameters is better, lets change to that.

Regarding `_`
both 
`https://busapi.amithv.xyz/api/v1/schedules/HIGH_COURT_JUNCTION/ERNAKULAM_SOUTH?time=12:00` and
`https://busapi.amithv.xyz/api/v1/schedules/HIGH COURT JUNCTION/ERNAKULAM SOUTH?time=12:00` works.

@subins2000 suggested adding a replacement for `_` in the backend in case someone prefers to use `_` instead of a space.

**Comment by subins2000** [comment]
@amith-vp On a rethink, drop the support for underscores since now it's gonna use query params. Space looks ugly in URL pathname but looks alright when used as query param (+ instead of %20)

**Comment by amith-vp** [comment]
Changed
